[project]
name = "sotooh"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "vmzhelifonov-hub", email = "volodya.zhelifonov@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
sotooh = "sotooh:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
