# Generated by Django 5.1.15 on 2026-09-21 09:55

import apps.catalog.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("product", "Product"), ("service", "Service")],
                        default="product",
                        max_length=12,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("solar_panel", "Solar Panel"),
                            ("inverter", "Inverter"),
                            ("battery", "Battery"),
                            ("mounting", "Mounting"),
                            ("protection", "Protection"),
                            ("cable", "Cable"),
                            ("accessory", "Accessory"),
                            ("installation", "Installation"),
                            ("service", "Service"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=120)),
                ("model", models.CharField(blank=True, max_length=120)),
                ("sku", models.CharField(blank=True, max_length=64)),
                ("name_ar", models.CharField(max_length=255)),
                ("name_en", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "cost_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "selling_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("currency", models.CharField(default="IQD", max_length=3)),
                ("warranty_months", models.PositiveIntegerField(default=0)),
                ("unit", models.CharField(default="pcs", max_length=20)),
                ("active", models.BooleanField(default=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.catalog.models.product_image_path,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "active"],
                        name="catalog_pro_organiz_99006a_idx",
                    ),
                    models.Index(
                        fields=["organization", "category"],
                        name="catalog_pro_organiz_b118e1_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("sku", ""), _negated=True),
                        fields=("organization", "sku"),
                        name="uniq_org_sku",
                    )
                ],
            },
        ),
    ]
