# Generated by Django 5.1.15 on 2026-09-21 09:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("catalog", "0001_initial"),
        ("crm", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quote_number",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("currency", models.CharField(default="IQD", max_length=3)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=16),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=16),
                ),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5),
                ),
                (
                    "tax_percent",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=16),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=16),
                ),
                ("notes_ar", models.TextField(blank=True)),
                ("notes_en", models.TextField(blank=True)),
                ("payment_terms", models.TextField(blank=True)),
                ("delivery_terms", models.TextField(blank=True)),
                (
                    "share_token",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("share_enabled", models.BooleanField(default=False)),
                ("share_revoked_at", models.DateTimeField(blank=True, null=True)),
                ("first_viewed_at", models.DateTimeField(blank=True, null=True)),
                ("last_viewed_at", models.DateTimeField(blank=True, null=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("won_at", models.DateTimeField(blank=True, null=True)),
                ("lost_reason", models.CharField(blank=True, max_length=255)),
                ("pdf_url", models.CharField(blank=True, max_length=500)),
                ("pdf_generated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotes_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotes",
                        to="crm.customer",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PublicQuoteView",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("viewed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_views",
                        to="quotations.quote",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuoteItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=500)),
                ("brand_model", models.CharField(blank=True, max_length=255)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=Decimal("1.00"), max_digits=12),
                ),
                ("unit", models.CharField(default="pcs", max_length=20)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                (
                    "line_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=16),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quote_items",
                        to="accounts.organization",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.product",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="quotations.quote",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(fields=["organization", "status"], name="quotations__organiz_f5c4da_idx"),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["organization", "created_at"],
                name="quotations__organiz_fb0641_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(fields=["share_token"], name="quotations__share_t_996399_idx"),
        ),
    ]
